let allItems = [
  [
    [
      [
        "items/chicken/chicken_1/1/1.webp",
        "items/chicken/chicken_1/1/2.webp",
        "items/chicken/chicken_1/1/3.webp",
      ],
      "Chicken Curry cut - Small Pieces",
      "Juicy bone-in & boneless chicken for delectable curres.",
      "500 g",
      "12 - 18 Pieces",
      "Serves 4",
      "169",
    ],
    [
      [
        "items/chicken/chicken_1/2/1.webp",
        "items/chicken/chicken_1/2/2.webp",
        "items/chicken/chicken_1/2/3.webp",
      ],
      "Chicken Curry Cut - Small Pieces(Large Pack)",
      "The ideal pack for big, delicious curry feast.",
      "1000 g",
      "24 - 36 Pieces",
      "Serves 6",
      "325",
    ],
    [
      [
        "items/chicken/chicken_1/3/1.webp",
        "items/chicken/chicken_1/3/2.webp",
        "items/chicken/chicken_1/3/3.webp",
      ],
      "Chicken Curry Cut - Large Pieces",
      "Large bone in & boneless in pieces for a delicious curry.",
      "500 g",
      "8 - 10 Pieces",
      "Serves 4",
      "169",
    ],
    [
      [
        "items/chicken/chicken_1/4/1.webp",
        "items/chicken/chicken_1/4/2.webp",
        "items/chicken/chicken_1/4/3.webp",
      ],
      "Chicken Curry Cut - Large Pieces(Large Pack)",
      "Large bone in & boneless pieces for delicious curry.",
      "1000 g",
      "14 - 22 Pieces",
      "Serves 6",
      "325",
    ],
    [
      [
        "items/chicken/chicken_1/5/1.webp",
        "items/chicken/chicken_1/5/2.webp",
        "items/chicken/chicken_1/5/3.webp",
      ],
      "premium Chicken Leg Curry Cut",
      "Juicy bone-in leg pieces for delicious curries or biryanis.",
      "300 g",
      "4 - 6 Pieces",
      "Serves 2-3",
      "195",
    ],
    [
      [
        "items/chicken/chicken_1/6/1.webp",
        "items/chicken/chicken_1/6/2.webp",
        "items/chicken/chicken_1/6/3.webp",
      ],
      "temder Spring Chicken urry Cut",
      "Juicy , tender cuts from a whole spring chicken",
      "800 g",
      "14 - 16 Pieces",
      "Serves 5-6",
      "339",
    ],
    [
      [
        "items/chicken/chicken_1/7/1.webp",
        "items/chicken/chicken_1/7/2.webp",
        "items/chicken/chicken_1/7/3.webp",
      ],
      "Chciken Curry Cut With Skin - Small Pieces",
      "A Pop offflavour with skin-on chicken cuts.",
      "500 g",
      "12 - 14 Pieces",
      "Serves 4",
      "165",
    ],
    [
      [
        "items/chicken/chicken_1/8/1.jpg",
        "items/chicken/chicken_1/8/2.jpg",
        "items/chicken/chicken_1/8/3.jpg",
      ],
      "Country Chicken / NattuKoli Curry Cut",
      "The start of a flavourful meaty curry.",
      "550 g",
      "12 - 17 Pieces",
      "Serves 4",
      "429",
    ],
  ],
  [
    [
      [
        "items/chicken/chicken_2/1/1.jpg",
        "items/chicken/chicken_2/1/2.jpg",
        "items/chicken/chicken_2/1/3.jpg",
      ],
      "Premium Chicken Thigh Boneless",
      "Meaty, temder boneless chicken thighs.",
      "450 g",
      "3 - 7 Pieces",
      "Serves 5",
      "284",
    ],
    [
      [
        "items/chicken/chicken_2/2/1.jpg",
        "items/chicken/chicken_2/2/2.jpg",
        "items/chicken/chicken_2/2/3.jpg",
      ],
      "Chicken Breast - Boneless",
      "Enjoy tender pieces of (juicy chicken breast).",
      "450 g",
      "2 - 7 Pieces",
      "Serves 4",
      "305",
    ],
    [
      [
        "items/chicken/chicken_2/3/1.jpg",
        "items/chicken/chicken_2/3/2.jpg",
        "items/chicken/chicken_2/3/3.jpg",
      ],
      "Chicken Boneless - Mini Bites",
      "Juicy, temder godness of chicken in an mouthful.",
      "250 g",
      "20 - 30 Pieces",
      "Serves 4",
      "174",
    ],
    [
      [
        "items/chicken/chicken_2/4/1.jpg",
        "items/chicken/chicken_2/4/2.jpg",
        "items/chicken/chicken_2/4/3.jpg",
      ],
      "Chicken Mince(Keema)",
      "For mouth - watering meathalls keema & more.",
      "450 g",
      "",
      "Serves 4",
      "252",
    ],
    [
      [
        "items/chicken/chicken_2/5/1.jpg",
        "items/chicken/chicken_2/5/2.jpg",
        "items/chicken/chicken_2/5/3.jpg",
      ],
      "Chicken Breast Boneless (Large Pack)",
      "Skinless, boneless pieces of juicy chicken breasts.",
      "990 g",
      "4 - 7 Pieces",
      "Serves 6",
      "579",
    ],
    [
      [
        "items/chicken/chicken_2/6/1.jpg",
        "items/chicken/chicken_2/6/2.jpg",
        "items/chicken/chicken_2/6/3.jpg",
      ],
      "Chicken Mince - 100g(Personal Pack)",
      "for a burger a few kebabs or some keema.",
      "100 g",
      "",
      "Serves 1-2",
      "99",
    ],
    [
      [
        "items/chicken/chicken_2/7/1.jpg",
        "items/chicken/chicken_2/7/2.jpg",
        "items/chicken/chicken_2/7/3.jpg",
      ],
      "Premium Chicken LegBoneless Cubes",
      "12-15 boneless leg and thigh pieces .",
      "450 g",
      "12 - 16 Pieces",
      "Serves 2-3",
      "355",
    ],
    [
      [
        "items/chicken/chicken_2/8/1.jpg",
        "items/chicken/chicken_2/8/2.jpg",
        "items/chicken/chicken_2/8/3.jpg",
      ],
      "Chicken Thigh Boneless (Mini Pack)",
      "Meaty, tender boneless chicken  thighs.",
      "200 g",
      "",
      "",
      "179",
    ],
    [
      [
        "items/chicken/chicken_2/9/1.jpg",
        "items/chicken/chicken_2/9/2.jpg",
        "items/chicken/chicken_2/9/3.jpg",
      ],
      "Chicken Mince/Keema - 250g(Mini-Pack)",
      "Tender, perfectly ground meat.",
      "250 g",
      "",
      "Serves 2-3",
      "199",
    ],
    [
      [
        "items/chicken/chicken_2/10/1.jpg",
        "items/chicken/chicken_2/10/2.jpg",
        "items/chicken/chicken_2/10/3.jpg",
      ],
      "Chicken Tenders Boneless",
      "Get a bite of boneless delicious with this chicken cut.",
      "350 g",
      "9 - 15 Pieces",
      "Serves 2 - 3",
      "299",
    ],
  ],
  [
    [
      [
        "items/chicken/chicken_3/1/1.jpg",
        "items/chicken/chicken_3/1/2.jpg",
        "items/chicken/chicken_3/1/3.jpg",
      ],
      "Chicken Drumstick - Pack Of 6",
      "Juicy bone-in chicken drumsticks, cut from the leg.",
      "",
      "6 Pieces",
      "Serves 2-3",
      "289",
    ],
    [
      [
        "items/chicken/chicken_3/2/1.webp",
        "items/chicken/chicken_3/2/2.webp",
        "items/chicken/chicken_3/2/3.jpg",
      ],
      "Classic Chicken Biryani Cut",
      "5 Juicy pieces for delicious biryanis.",
      "",
      "5 Pieces",
      "Serves 2 - 3 ",
      "199",
    ],
    [
      [
        "items/chicken/chicken_3/3/1.jpg",
        "items/chicken/chicken_3/3/2.jpg",
        "items/chicken/chicken_3/3/3.jpg",
        "items/chicken/chicken_3/3/4.jpg",
      ],
      "Classic Chicken Soup Bones",
      "Cleaned chicken bones for a delicious flavourful stack.",
      "250 g",
      "11 - 12 Pieces",
      "",
      "75",
    ],
    [
      [
        "items/chicken/chicken_3/4/1.jpeg",
        "items/chicken/chicken_3/4/2.jpeg",
        "items/chicken/chicken_3/4/3.jpeg",
      ],
      "Chicken Drumsticks - pack of 2(Mini Pack)",
      "Juicy bone-in chicken drumstick, cut from the leg.",
      "",
      "2 Pieces",
      "Serves 1-2",
      "109",
    ],
    [
      [
        "items/chicken/chicken_3/5/1.jpeg",
        "items/chicken/chicken_3/5/2.jpeg",
        "items/chicken/chicken_3/5/3.jpeg",
      ],
      "Premium Chicken Leg Boneless Cubes",
      "12 - 15 boneless leg and thigh pieces.",
      "450 g",
      "12 - 16 Pieces",
      "Serves 2-3",
      "355",
    ],
    [
      [
        "items/chicken/chicken_3/6/1.jpeg",
        "items/chicken/chicken_3/6/2.jpeg",
        "items/chicken/chicken_3/6/3.jpeg",
      ],
      "Premium Chicken Tangdi Biryani Cut",
      "Juicy, Tender chicken drumsticks & wholethigh pieces.",
      "550 g",
      "6 Pieces",
      "Serves 2-3",
      "276",
    ],
    [
      [
        "items/chicken/chicken_3/7/1.jpeg",
        "items/chicken/chicken_3/7/2.jpeg",
        "items/chicken/chicken_3/7/3.jpeg",
      ],
      "chicken Leg With Thigh - pack of 2",
      "Juicy bone-in leg pieces for dfelicious curries or biriyanis .",
      "",
      "3 Pieces",
      "Serves 2-3",
      "375",
    ],
    [
      [
        "items/chicken/chicken_3/8/1.jpeg",
        "items/chicken/chicken_3/8/2.jpeg",
        "items/chicken/chicken_3/8/3.jpeg",
      ],
      "Chicken Lollipop - pack of 10",
      "10 pieces of meaty chicken lollipops.",
      "",
      "10 Pieces",
      "serves 2",
      "195",
    ],
    [
      [
        "items/chicken/chicken_3/9/1.jpeg",
        "items/chicken/chicken_3/9/2.jpeg",
        "items/chicken/chicken_3/9/3.jpeg",
      ],
      "Chicken65 Fry Cut",
      "12 - 15 bone-in, breast and leg fry cut pieces.",
      "250 g",
      "12 - 15 Pieces",
      "Serves 2-3",
      "99",
    ],
    [
      [
        "items/chicken/chicken_3/10/1.jpeg",
        "items/chicken/chicken_3/10/2.jpeg",
        "items/chicken/chicken_3/10/3.jpeg",
      ],
      "Chicken Wings With Skin",
      "cut & clenaed chicken wings with skin.",
      "430 g",
      "6 - 8 Pieces",
      "Serves 4",
      "135",
    ],
  ],
  [
    [
      [
        "items/chicken/chicken_4/1/1.jpeg",
        "items/chicken/chicken_4/1/2.jpeg",
        "items/chicken/chicken_4/1/3.jpeg",
      ],
      "Chicken Liver",
      "Smooth, rich & meaty chicken liver.",
      "350 g",
      "7 - 9 Pieces",
      "Serves 2-3",
      "85",
    ],
    [
      [
        "items/chicken/chicken_4/2/1.jpeg",
        "items/chicken/chicken_4/2/2.jpeg",
        "items/chicken/chicken_4/2/3.jpeg",
      ],
      "Chicken Gizzard",
      "Rich savoury & full odf meaty chicken flavours.",
      "300 g",
      "14 - 16 Pieces",
      "Serves 2-3",
      "109",
    ],
  ],
  [
    [
      [
        "items/chicken/chicken_5/1/1.jpeg",
        "items/chicken/chicken_5/1/1.jpeg",
        "items/chicken/chicken_5/1/1.jpeg",
      ],
      "japanese Quail (whole) - Pack of 2",
      "a Weekend Special, Perfect as a Starter for Curries.",
      "",
      "2 Pieces",
      "Serves 1-2",
      "249",
    ],
  ],
  [
    [
      [
        "items/chicken/chicken_1/5/1.webp",
        "items/chicken/chicken_1/5/2.webp",
        "items/chicken/chicken_1/5/3.webp",
      ],
      "premium Chicken Leg Curry Cut",
      "Juicy bone-in leg pieces for delicious curries or biryanis.",
      "300 g",
      "4 - 6 Pieces",
      "Serves 2-3",
      "195",
    ],
    [
      [
        "items/chicken/chicken_2/7/1.jpg",
        "items/chicken/chicken_2/7/2.jpg",
        "items/chicken/chicken_2/7/3.jpg",
      ],
      "Premium Chicken LegBoneless Cubes",
      "12-15 boneless leg and thigh pieces .",
      "450 g",
      "12 - 16 Pieces",
      "Serves 2-3",
      "355",
    ],
    [
      [
        "items/chicken/chicken_3/6/1.jpeg",
        "items/chicken/chicken_3/6/2.jpeg",
        "items/chicken/chicken_3/6/3.jpeg",
      ],
      "Premium Chicken Tangdi Biryani Cut",
      "Juicy, Tender chicken drumsticks & wholethigh pieces.",
      "550 g",
      "6 Pieces",
      "Serves 2-3",
      "276",
    ],
    [
      [
        "items/chicken/chicken_1/8/1.jpg",
        "items/chicken/chicken_1/8/2.jpg",
        "items/chicken/chicken_1/8/3.jpg",
      ],
      "Country Chicken / NattuKoli Curry Cut",
      "The start of a flavourful meaty curry.",
      "550 g",
      "12 - 17 Pieces",
      "Serves 4",
      "429",
    ],
    [
      [
        "items/chicken/chicken_3/4/1.jpeg",
        "items/chicken/chicken_3/4/2.jpeg",
        "items/chicken/chicken_3/4/3.jpeg",
      ],
      "Chicken Drumsticks - pack of 2(Mini Pack)",
      "Juicy bone-in chicken drumstick, cut from the leg.",
      "",
      "2 Pieces",
      "Serves 1-2",
      "109",
    ],
    [
      [
        "items/chicken/chicken_2/10/1.jpg",
        "items/chicken/chicken_2/10/2.jpg",
        "items/chicken/chicken_2/10/3.jpg",
      ],
      "Chicken Tenders Boneless",
      "Get a bite of boneless delicious with this chicken cut.",
      "350 g",
      "9 - 15 Pieces",
      "Serves 2 - 3",
      "299",
    ],
    [
      [
        "items/chicken/chicken_3/7/1.jpeg",
        "items/chicken/chicken_3/7/2.jpeg",
        "items/chicken/chicken_3/7/3.jpeg",
      ],
      "chicken Leg With Thigh - pack of 3",
      "Juicy bone-in leg pieces for dfelicious curries or biriyanis .",
      "",
      "3 Pieces",
      "Serves 2-3",
      "375",
    ],
  ],
];

export default allItems;
